version: '3.1'

services:
  wordpress:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes: 
      - site_files:/var/www/html
      - ./content:/var/www/html/wp-content
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_DATABASE: wordpress
      WORDPRESS_DB_PASSWORD: password
    networks:
      - wpsite

  nginx:
    image: nginx:latest
    container_name: mywebsite-nginx
    ports:
      - '8000:80'
    volumes: 
      - site_files:/var/www/html
      - ./content:/var/www/html/wp-content
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    restart: always
    networks:
      - wpsite
  db:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - wpsite
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite


networks:
  wpsite:
volumes:
  site_files: {}
  db_data: {}
